<?php $action = $this->getRequest()->getActionName(); ?>

<div class="appointment">

    <?php if ($action == "ajax"): ?>

    <?php endif; ?>

    <div class="page-title">
        <h1><?php echo $this->__("Made an appointment"); ?></h1>
    </div>

    <div class="fieldset">

        <form action="<?php echo $this->getUrl("appointments/index/save"); ?>" id="appointmentForm" method="post">

            <p class="form-info"><p>
            <div class="clearfix"></div>


            <ul class="form-list">
                <div class="col-lg-6 form-container">
                    <li class="fields">
                        <div class="field clearfix">
                            <label for="firstname" class="required"><em>*</em><?php echo $this->__("Firstname"); ?></label>
                            <div class="input-box">
                                <input name="firstname" value="" title="firstname" class="input-text  required-entry" id="firstname" type="text">
                            </div>
                        </div>
                    </li>    

                    <li class="fields">    
                        <div class="field">
                            <label for="lastname" class="required"><em>*</em><?php echo $this->__("Lastname"); ?></label>
                            <div class="input-box">
                                <input name="lastname" value="" title="lastname" class="input-text  required-entry" id="lastname" type="text">
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="email" class="required"><em>*</em><?php echo $this->__("Email"); ?></label>
                            <div class="input-box">
                                <input name="email" value="" title="email" class="input-text  required-entry validate-email" id="email" type="text">
                            </div>
                        </div>
                    </li>  

                    <li class="fields">   
                        <div class="field">
                            <label for="telephone" class="required"><em>*</em><?php echo $this->__("Telephone"); ?></label>
                            <div class="input-box">
                                <input name="telephone" value="" title="telephone" class="input-text  required-entry" id="telephone" type="text">
                            </div>
                        </div>
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="message" class="required"><em>*</em><?php echo $this->__("Message"); ?></label>
                            <div class="input-box">
                                <textarea class="input-text required-entry" name="message"></textarea>
                            </div>
                        </div>
                    </li> 

                    <li class="fields">    
                        <div class="field">
                            <div class="buttons-set">
                                <p class="required">* <?php echo $this->__("requred fields"); ?></p>
                                <button type="submit" title="Wyślij" class="button"><span><?php echo $this->__("Wyślij"); ?></span></button>
                            </div>
                        </div>
                    </li>

                </div>
                <div class="clearfix"></div>
            </ul>


            <div class="clearfix"></div>

        </form>

        <script type="text/javascript">
            //<![CDATA[
            var appointmentForm = new VarienForm('appointmentForm', true);
            //]]>
        </script>

    </div>

</div>